apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-regel-grunnlag
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 3
    max: 3
  kafka:
    pool: "{{ kafka.pool }}"
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 30m
      memory: 512Mi
  secureLogs:
    enabled: true
  env:
    - name: JAVA_OPTS
      value: -XX:+UseParallelGC -XX:MaxRAMPercentage=50.0 -XX:ActiveProcessorCount=4
  envFrom:
    - secret: dp-regel-grunnlag-unleash-api-token
  accessPolicy:
    outbound:
      external:
        - host: dagpenger-unleash-api.nav.cloud.nais.io
