apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-regel-grunnlag
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 3
    max: 3
  kafka:
    pool: {{ kafka.pool }}
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 300m
      memory: 512Mi
  secureLogs:
    enabled: true
